{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "probes-using-scripts.serviceAccountName" . }}
  labels:
{{ include "probes-using-scripts.labels" . | indent 4 }}
{{- end -}}
