---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false
  # <% if ENV['PACKAGE'] %>
  # attributes:
  #   extra_vars:
  #     package: "<%= ENV['PACKAGE'] %>"
  # <% end %>

platforms:
  - name: centos-7
    driver_config:
      image: centos:7
      run_command: "/usr/sbin/init"
      privileged: true
      use_sudo: true
  - name: ubuntu-18.04
    driver_config:
      image: ubuntu:18.04
      run_command: "/sbin/init"
      privileged: true
      use_sudo: true

suites:
  - name: es-7
    provisioner:
      idempotency_test: false
      playbook: main.yml
  - name: es-6
    provisioner:
      idempotency_test: false
      playbook: main.yml
      attributes:
        extra_vars:
          major_version: 6.x
