---
- hosts: localhost
  tasks:
    - name: add yum repository
      yum_repository:
        name: elasticsearch-7.x
        state: present
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        description: Elasticsearch repository for 7.x packages
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    - name: install elasticsearch package
      yum:
        name: elasticsearch
        state: present
    - name: start elasticsearch
      systemd:
        name: elasticsearch
        state: started
        daemon_reload: yes
    - name: install tools
      yum:
        name: "{{ item }}"
        state: present
      loop:
          - jq
          - vim
